name: flutter_avif_platform_interface
description: Common platform interface for the flutter_avif plugin.
version: 2.5.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_platform_interface

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  ffi: ^2.1.0
  protobuf: ^3.1.0
  isolate: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  ffigen: ^14.0.1