name: flutter_avif_web
description: Web implementation for flutter_avif.
version: 2.5.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_web

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_avif_platform_interface: ^2.5.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      web:
        pluginClass: FlutterAvifWeb
        fileName: flutter_avif_web.dart
  assets:
    - web/
